### ISSUE TITLE
Resources in nav menu

### ISSUE THREAD

**Issue by ahatherly** [nhsconnect/FHIR-ODS-API#6]
The left nav menu has a resources section, but only the "Organization" resource is listed in that menu.

On the resources overview page (https://developer.nhs.uk/apis/ods/explore.html) there are three resources linked ("Organization", "ValueSet" and "CodeSystem") - should all three be in the side nav too?

**Comment by jlellison** [comment]
They have been reinstated along with CapabilityStatement in the latest version 1.0.0-beta.
