### ISSUE TITLE
Custom Search Param

### ISSUE THREAD

**Issue by swk003** [nhsconnect/FHIR-ODS-API#8]
The 'ods-org-role' and 'ods-org-primaryRole' custom search params both have different paths but the same description.  See https://nhsconnect.github.io/FHIR-ODS-API/restfulapis_identification_organization.html.

The Extension-ODSAPI-OrganizationRole-1 is not published in the NHS FHIR Reference Server. Having looked at simplifier test ODS Lookup API definition i can see the extension can be 'used to describe what an Organization does and whether this is the primary role of the Organization' however it is not clear what the usage is for the 2 diff custom search params.

**Comment by IOPS-DEV** [comment]
This will be updated in the next release of the Implementation Guide.  The FHIR resources are yet to be published as the NHS FHIR Server does not have functionality required to support all the assets.
